version: '1'
services:
  pharmacyos-be:
    image: ghcr.io/future-arc/pharmacyos-be/main:latest  # use existing image from ghcr...
    container_name: pharmacyos-be
    env_file: ./.env
    environment:
      - PORT=${PORT}
      - DB_URL=${DB_URL}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo  
#  mongo:
#    image: mongo:latest
#    ports:
#      - "27017:27017"