version: '1'
services:
  pharmacyos-be:
    image: ghcr.io/future-arc/pharmacyos-be/main:latest  # use existing image from ghcr...
    container_name: pharmacyos-be
    env_file: 
      - ./backend/.env
    ports:
      # - "${PORT}:${PORT}"
      - 3000:3000
    depends_on:
      - mongo  
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"