 name: Push to GHCR and Deploy to VM

 on:
   push:
     branches:
       - main
       - setup_ci_cd
       - ci-cd-fixes

 jobs:
   push-and-deploy:
     runs-on: ubuntu-latest
     permissions:
       packages: write
       contents: read
     env:
       DB_URL: mongodb://mongo:27017/${{ vars.DB_NAME }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
#         with:
#           ref: main
       - name: Use Node.js
         uses: actions/setup-node@v2
         with:
           node-version: '18'
       - name: Install dependencies
         run: yarn --frozen-lockfile

       - name: Login to GitHub Packages
         uses: docker/login-action@v3
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}

       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
       - name: Build and push docker image
         uses: docker/build-push-action@v2
         with:
           context: .
           file: ./docker/DockerfileStaging
           push: true
           tags: |
             ghcr.io/{{ github.repository }}:${{ github.sha }}
         env:
           EXT_PORT:  ${{ vars.PORT }}
           INT_PORT:  ${{ vars.PORT }}
       -
         name: Remote docker login to Github docker registry and create/update .env file for docker compose
         uses: fifsky/ssh-action@master
         with:
           command: |
             echo ${{ secrets.DOCKER_REGISTRY_READ }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
             touch /srv/www/pharma-os/.env
             echo PORT={{ vars.PORT }}
             echo DB_URL=mongodb://mongo:27017/${{ vars.DB_NAME }} > /srv/www/pharma-os/.env
           host: ${{ secrets.STAGING_BE_HOST }}
           user: www
           key: ${{ secrets.STAGING_BE_HOST_PRIVATE_KEY }}
       -
         name: Deploy to Docker Host
         uses: wshihadeh/docker-deployment-action@master
         with:
           remote_docker_host: www@${{ secrets.STAGING_BE_HOST }}
           ssh_private_key: ${{ secrets.STAGING_BE_HOST_PRIVATE_KEY }}
           ssh_public_key: ${{ secrets.STAGING_BE_HOST_SERVER_PUBLIC_KEY }}
           stack_file_name: staging-docker-compose.yml
           deployment_mode: docker-compose
           args: --env-file /srv/www/platform-api-compose/.env up -d
           docker_prune: 'true'
           deploy_path: '/srv/www/platform-api-compose'
           copy_stack_file: 'true'
           pull_images_first: 'true'